name: CI

on:
  push:
    branches:
      - '**'
  pull_request:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build (Node 22)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Update Browserslist DB (non-blocking)
        run: npx --yes update-browserslist-db@latest || true

      - name: Build
        env:
          CI: 'true'
          GATSBY_TELEMETRY_DISABLED: '1'
          NODE_ENV: production
        run: npm run build

