name: CI

on:
  push:
    branches:
      - '**'
  pull_request:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint (ESLint + Prettier)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: ESLint
        run: npm run lint

      - name: Prettier check
        run: npm run format:check

  build:
    name: Build (Node 22)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Update Browserslist DB (non-blocking)
        run: npx --yes update-browserslist-db@latest || true

      - name: Build
        env:
          CI: 'true'
          GATSBY_TELEMETRY_DISABLED: '1'
          NODE_ENV: production
        run: npm run build

  smoke:
    name: Smoke tests (static routes)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build
        env:
          CI: 'true'
          GATSBY_TELEMETRY_DISABLED: '1'
          NODE_ENV: production
        run: npm run build

      - name: Check core routes exist
        run: |
          set -euo pipefail
          test -f public/index.html
          test -f public/blog/index.html
          test -f public/galleries/index.html
          test -f public/talks/index.html

      - name: Check at least one blog article and gallery generated
        run: |
          set -euo pipefail
          ls public/blog/*/*/*/*/index.html 1>/dev/null 2>&1 || (echo "No blog article pages found" && exit 1)
          ls public/galleries/*/index.html 1>/dev/null 2>&1 || (echo "No gallery pages found" && exit 1)
